TIER_BONUS = {
  "System-Biased-Cities": 0.0,  
  "Major-Cities": 50.0,  
  "Tourism/Business": 100.0, 
  "National-Capitals": 150.0, 
  "Regular-Cities": 200.0 
}

AIRPORT_TIER = {
  # Major Cities
  "JFK": "Major-Cities",
  "LAX": "Major-Cities",
  "ORD": "Major-Cities",
  "LHR": "Major-Cities",
  "CDG": "Major-Cities",
  "NRT": "Major-Cities",
  "BER": "Major-Cities",
  "SVO": "Major-Cities",
  "PVG": "Major-Cities",
  "ICN": "Major-Cities",
  "GRU": "Major-Cities",
  "YVR": "Major-Cities",
  "DXB": "Major-Cities",
  "IST": "Major-Cities",

  # Tourism/Business Cities
  "MIA": "Tourism/Business",
  "BKK": "Tourism/Business",
  "SYD": "Tourism/Business",
  "CPT": "Tourism/Business",
  "GIG": "Tourism/Business",
  "OPO": "Tourism/Business",
  "FCO": "Tourism/Business",
  "ATH": "Tourism/Business",
  "HKG": "Tourism/Business",
  "BCN": "Tourism/Business",
  "DUB": "Tourism/Business",
  "MEX": "Tourism/Business",
  "SFO": "Tourism/Business",
  "IST": "Tourism/Business",
  "HAV": "Tourism/Business",
  "BCN": "Tourism/Business",
  "NAP": "Tourism/Business",
  "BGY": "Tourism/Business",
  "MXP": "Tourism/Business",
  "JJN": "Tourism/Business",
  "CGO": "Tourism/Business",
  "WUH": "Tourism/Business",
  "SIN": "Tourism/Business",
  "SGN": "Tourism/Business",
  "BKI": "Tourism/Business",
  "PRG": "Tourism/Business",


  # National Capitals
  "LIS": "National-Capitals",
  "BRU": "National-Capitals",
  "VIE": "National-Capitals",
  "ARN": "National-Capitals",
  "WAW": "National-Capitals",
  "BUD": "National-Capitals",
  "SCL": "National-Capitals",
  "DEL": "National-Capitals",
  "CAI": "National-Capitals",
  "KHI": "National-Capitals",
  "JNB": "National-Capitals",
  "NBO": "National-Capitals",
  "ADD": "National-Capitals",
  "DSS": "National-Capitals",
  "BSB": "National-Capitals",
  "YOW": "National-Capitals",
  "IAD": "National-Capitals",
  "KIN": "National-Capitals",
  "GUA": "National-Capitals",
  "BZE": "National-Capitals",
  "SAL": "National-Capitals",
  "TGU": "National-Capitals",
  "MGA": "National-Capitals",
  "SJO": "National-Capitals",
  "PTY": "National-Capitals",
  "BOG": "National-Capitals",
  "CCS": "National-Capitals",
  "LIM": "National-Capitals",
  "SCL": "National-Capitals",
  "EZE": "National-Capitals",
  "AEP": "National-Capitals",
  "ASU": "National-Capitals",
  "VVI": "National-Capitals",
  "LPB": "National-Capitals",
  "MAD": "National-Capitals",
  "CPH": "National-Capitals",
  "OSL": "National-Capitals",
  "HEL": "National-Capitals",
  "TLL": "National-Capitals",
  "RIX": "National-Capitals",
  "VNO": "National-Capitals",
  "MSQ": "National-Capitals",
  "RMO": "National-Capitals",
  "OTP": "National-Capitals",
  "BEG": "National-Capitals",
  "ZRH": "National-Capitals",
  "BOJ": "National-Capitals",
  "SJJ": "National-Capitals",
  "FNJ": "National-Capitals",
  "MEL": "National-Capitals",
  "AKL": "National-Capitals",
  "ZAG": "National-Capitals",
  "KEF": "National-Capitals",
}